"""Added order item other details

Revision ID: 0f4c23dc59da
Revises: 5d8666b21ddd
Create Date: 2025-03-19 08:02:54.448266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4c23dc59da'
down_revision = '5d8666b21ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('others', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_order_items', schema=None) as batch_op:
        batch_op.drop_column('others')

    # ### end Alembic commands ###
