"""Added pdf and gift image

Revision ID: 5d8666b21ddd
Revises: 900a1ea64ec3
Create Date: 2025-03-18 12:21:59.217521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8666b21ddd'
down_revision = '900a1ea64ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gift_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_order_items', schema=None) as batch_op:
        batch_op.drop_column('gift_image')
        batch_op.drop_column('pdf_file')

    # ### end Alembic commands ###
