"""Create core exports

Revision ID: 900a1ea64ec3
Revises: af29180a524a
Create Date: 2025-03-17 11:38:16.115079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900a1ea64ec3'
down_revision = 'af29180a524a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('export_type', sa.String(length=190), nullable=False),
    sa.Column('export_options', sa.JSON(), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=190), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_exports')
    # ### end Alembic commands ###
