"""Added status columns

Revision ID: af29180a524a
Revises: cb57b94ed620
Create Date: 2025-03-15 17:55:29.821110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af29180a524a'
down_revision = 'cb57b94ed620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=190), nullable=True))
        batch_op.add_column(sa.Column('properties', sa.JSON(), nullable=True))

    with op.batch_alter_table('core_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=190), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_orders', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('mail_sent')

    with op.batch_alter_table('core_order_items', schema=None) as batch_op:
        batch_op.drop_column('properties')
        batch_op.drop_column('status')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
