"""create_orders

Revision ID: c6bbcc1e6958
Revises: d52f986d3efd
Create Date: 2025-03-11 10:10:41.535339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bbcc1e6958'
down_revision = 'd52f986d3efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_orders',
    sa.Column('id', sa.String(length=190), nullable=False),
    sa.Column('order_number', sa.String(length=190), nullable=False),
    sa.Column('customer_name', sa.String(length=190), nullable=True),
    sa.Column('customer_email', sa.String(length=190), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_order_items',
    sa.Column('id', sa.String(length=190), nullable=False),
    sa.Column('order_id', sa.String(length=190), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('custom_design', sa.String(length=190), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=190), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['core_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_order_items')
    op.drop_table('core_orders')
    # ### end Alembic commands ###
