"""Added order item attachments

Revision ID: cb57b94ed620
Revises: c6bbcc1e6958
Create Date: 2025-03-11 17:10:14.201905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb57b94ed620'
down_revision = 'c6bbcc1e6958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_order_item_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.String(length=190), nullable=False),
    sa.Column('name', sa.String(length=190), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=190), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['core_order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_order_item_attachments')
    # ### end Alembic commands ###
