"""Initial

Revision ID: d52f986d3efd
Revises: 
Create Date: 2025-03-10 08:38:12.568738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52f986d3efd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_shopify_webhooks',
    sa.Column('id', sa.String(length=190), nullable=False),
    sa.Column('shopify_id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=190), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=190), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mfa_secret')
    )
    op.create_table('core_auth_refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=190), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_auth_refresh_tokens')
    op.drop_table('core_users')
    op.drop_table('core_shopify_webhooks')
    # ### end Alembic commands ###
